// https://docs.google.com/spreadsheets/d/1zK1hccukAVkmWxxASSbjzqq-LQVIX_11/edit?gid=1013312483#gid=1013312483
const PASSAGES = [
    {
      id: "p1",
      text: "Many years ago, an Emperor was so excessively fond of new clothes that he spent all his money on them. He did not trouble himself in the least about his soldiers, nor did he care to go to the theatre or the horse races, except if the occasions allowed him to show off his new clothes. He had a different suit for each hour of the day. Like any other king or emperor, one is accustomed to saying, 'He is sitting in council. 'Instead, his advisors always said, 'The Emperor is sitting in his wardrobe.' Time passed away merrily in the large capital city. Strangers arrived every day at the fashionable king’s court. One day, two rogues, calling themselves weavers, made an appearance. They mentioned that they knew how to weave fabrics with the most beautiful colors and elaborate patterns. They claimed that the clothes had the extraordinary property of remaining invisible to everyone who was unfit for the office he held or was exceedingly simple. 'These must indeed be splendid clothes!' thought the Emperor. 'Had I such a suit, I might, at once, find out which men in my realms are unfit for their office and I would also be able to distinguish the wise from the foolish! This fine fabric must be woven for me immediately.' And he ordered large sums of money to be given to both the weavers so they could begin their work immediately. So the two pretending weavers set up two looms and began to work very busily. In reality, they did nothing at all. They asked for the most delicate silk and the purest gold thread but put both into their own knapsacks, and then, they continued pretending to work at the empty looms until late at night.",
      GL: "8",
      FRE: "63.235",
      dict: {
        about:         ["acerca de", "sobre"],
        accustomed:    ["acostumbrado"],
        advisors:      ["consejeros"],
        allowed:       ["permitía", "permitió"],
        appearance:    ["aparición", "apariencia"],
        arrived:       ["llegaban", "llegaron"],
        beautiful:     ["hermoso", "bello"],
        both:          ["ambos"],
        busily:        ["afanosamente", "atareadamente"],
        calling:       ["llamándose", "haciéndose llamar"],
        capital:       ["capital"],
        claimed:       ["afirmaron", "aseguraron"],
        clothes:       ["ropa"],
        continued:     ["continuaron", "siguieron"],
        could:         ["podían", "podrían"],
        council:       ["consejo"],
        court:         ["corte"],
        delicate:      ["delicada"],
        did:           ["hizo", "hacía"],
        different:     ["diferente", "distinto"],
        distinguish:   ["distinguir"],
        each:          ["cada"],
        elaborate:     ["elaborados", "complejos"],
        emperor:       ["emperador"],
        everyone:      ["todos", "todo el mundo"],
        exceedingly:   ["sumamente", "extremadamente"],
        excessively:   ["excesivamente"],
        extraordinary: ["extraordinaria"],
        fabrics:       ["telas", "tejidos"],
        fashionable:   ["elegante", "de moda"],
        foolish:       ["necio", "tonto"],
        himself:       ["sí mismo"],
        horse:         ["caballo"],
        hour:          ["hora"],
        immediately:   ["inmediatamente"],
        instead:       ["en cambio", "en su lugar"],
        invisible:     ["invisible"],
        knapsacks:     ["morrales", "mochilas"],
        knew:          ["sabían", "conocían"],
        least:         ["menos", "lo más mínimo"],
        looms:         ["telares"],
        mentioned:     ["mencionaron"],
        merrily:       ["alegremente"],
        might:         ["podría", "podía"],
        night:         ["noche"],
        nothing:       ["nada"],
        occasions:     ["ocasiones"],
        ordered:       ["ordenó"],
        other:         ["otro"],
        out:           ["fuera", "afuera"],
        patterns:      ["patrones", "diseños"],
        pretending:    ["fingiendo"],
        property:      ["propiedad", "cualidad"],
        reality:       ["realidad"],
        realms:        ["reinos"],
        remaining:     ["permanecer", "que permanecía"],
        rogues:        ["pícaros", "bribones"],
        said:          ["dijeron", "dijo"],
        show:          ["mostrar", "presumir"],
        sitting:       ["sentado"],
        soldiers:      ["soldados"],
        splendid:      ["espléndida", "magnífica"],
        strangers:     ["extraños", "forasteros"],
        theatre:       ["teatro"],
        themselves:    ["sí mismos"],
        thought:       ["pensó", "pensamiento"],
        thread:        ["hilo"],
        trouble:       ["molestarse", "preocuparse"],
        wardrobe:      ["guardarropa", "vestidor"],
        weave:         ["tejer"],
        weavers:       ["tejedores"],
        which:         ["cuál", "que"],
        would:         ["haría", "sería"],
        years:         ["años"]
      },
      questions: [
        { q: "What did the Emperor not trouble himself with?", options: ["Strangers", "Councilmen", "Horse races", "Soldiers"] , answer: "D"},
        { q: "What did the weavers ask for?", options: ["The most delicate and pure gold silk thread.", "The most delicate silk and the purest gold thread.", "The most delicate silk and the purest silver thread.", "The most delicate satin and the purest gold thread."], answer: "B" },
        { q: "Which is a property about the clothes?", options: ["Remaining invisible to those extraordinarily simple in character", "Remaining invisible to the council", "Remaining invisible to the military", "Remaining invisible to townsfolk"], answer: "A" }
      ]
    },


    {
      id: "p2",
      text: "Born in 1925, Medgar Evers grew up under segregation in the deep South. He walked 12 miles daily to get to school, eventually earning his high school diploma. Evers served in the U.S. Army from 1943 to 1945, including as a sergeant at the Battle of Normandy. After the war, he attended and studied business at a historically black college now known as Alcorn State University, and he graduated in 1952 and moved to Mound Bayou, Mississippi—a town developed by African Americans. As a military veteran who fought for his country, Evers expected that he would be able to vote. However, he and five friends were deterred at gunpoint. Racism denied his equal rights. Later, he organized boycotts of gas stations with the slogan “Don’t Buy Gas Where You Can’t Use the Restroom.” To fight state laws that made segregation legal, Evers applied to attend the University of Mississippi Law School, but his application was rejected because of his race. That same year, Evers was named the NAACP's first field secretary for Mississippi. In this position, he helped organize boycotts and set up new local chapters of the NAACP. He tried to desegregate public beaches, buses, and parks. Evers led voter registration drives, advocated for school integration, and led investigations into the murder of the teenager Emmett Till. Evers was a prominent black voice, and that made him a target. In the 1960s, civil rights activists lived under constant threat. In May 1963, a bomb was thrown into his garage, and then someone tried to hit him with a car. In June 1963, Evers returned home without his usual FBI or police escort. As he got out of his car, carrying a box of NAACP t-shirts that said “Jim Crow Must Go,” Medgar Evers was shot and killed. Mourned nationally, Evers was buried in Arlington National Cemetery, where he received full military honors.",      GL: "8.4",
      FRE: "61.5",
      dict: {
        activists:     ["activistas"],
        advocated:     ["abogó", "defendió"],
        african:       ["africano", "afroamericano"],
        alcorn:        ["Alcorn"],
        americans:     ["estadounidenses", "americanos"],
        applied:       ["solicitó", "postuló"],
        application:   ["solicitud"],
        Arlington:     ["Arlington"],
        attended:      ["asistió"],
        Bayou:         ["Bayou"],
        beaches:       ["playas"],
        because:       ["porque"],
        bomb:          ["bomba"],
        boycotts:      ["boicots"],
        buried:        ["enterrado", "sepultado"],
        business:      ["negocios", "empresa"],
        carrying:      ["cargando", "llevando"],
        cemetery:      ["cementerio"],
        chapters:      ["capítulos", "delegaciones"],
        college:       ["universidad", "colegio universitario"],
        constant:      ["constante"],
        country:       ["país"],
        daily:         ["diariamente", "a diario"],
        deep:          ["profundo"],
        denied:        ["negó", "denegó"],
        desegregate:   ["desegregar", "eliminar la segregación"],
        deterred:      ["disuadidos", "detenidos"],
        developed:     ["desarrollado", "fundado"],
        diploma:       ["diploma"],
        earning:       ["obteniendo", "ganando"],
        eventually:    ["finalmente", "con el tiempo"],
        evers:         ["Evers"],
        expected:      ["esperaba"],
        field:         ["de campo"],
        fight:         ["luchar", "combatir"],
        fought:        ["luchó", "combatió"],
        friends:       ["amigos"],
        graduated:     ["se graduó"],
        gunpoint:      ["a punta de pistola"],
        high:          ["secundaria", "alto"],
        historically:  ["históricamente"],
        however:       ["sin embargo"],
        including:     ["incluyendo"],
        integration:   ["integración"],
        investigations:["investigaciones"],
        known:         ["conocido"],
        medgar:        ["Medgar"],
        military:      ["militar"],
        Mississippi:   ["Misisipi"],
        mound:         ["Mound"],
        mourned:       ["llorado", "de luto por"],
        national:      ["nacional"],
        nationally:    ["a nivel nacional"],
        normandy:      ["Normandía"],
        organize:      ["organizar"],
        organized:     ["organizó"],
        out:           ["fuera", "afuera"],
        position:      ["puesto", "cargo"],
        prominent:     ["prominente", "destacado"],
        received:      ["recibió"],
        registration:  ["registro", "inscripción"],
        rejected:      ["rechazada"],
        restroom:      ["baño", "aseo"],
        returned:      ["regresó", "volvió"],
        rights:        ["derechos"],
        said:          ["decían", "decía"],
        school:        ["escuela"],
        secretary:     ["secretario"],
        segregation:   ["segregación"],
        sergeant:      ["sargento"],
        shirts:        ["camisetas"],
        shot:          ["disparado", "baleado"],
        someone:       ["alguien"],
        south:         ["sur"],
        stations:      ["estaciones", "gasolineras"],
        studied:       ["estudió"],
        teenager:      ["adolescente"],
        threat:        ["amenaza"],
        thrown:        ["arrojada", "lanzada"],
        tried:         ["intentó"],
        university:    ["universidad"],
        veteran:       ["veterano"],
        without:       ["sin"],
        would:         ["podría", "sería"],
        year:          ["año"],
      },
      questions: [
        { q: "How did Medgar Evers get to school everyday? ", options: ["He walked twelve miles to get there.", "He rode his bike.", "He took the bus, but he had to sit in the back.", "He walked to the black school in his neighborhood."], answer: "A"},
        { q: "What did Medger Evers NOT do? ", options: ["He tried to desegregate public beaches, buses, and parks.", "He led voter registration drives and advocated for school integration.", "He investigated the murder of the teenager Emmett Till.", "He led the 1955 Montgomery bus boycott."], answer: "D" },
        { q: "What happened at the end of Medgar Evers life? ", options: ["He was hit by a car while leaving the NAACP office.", "He was shot and killed when he returned home without a police escort.", "Someone threw a bomb into his kitchen while he was fixing dinner. ", "He was buried in his family cemetery after being killed."], answer: "B" }
      ]
    },


    {
      id: "p3",
      text: "The Russo-Japanese War took place between the Empire of Japan and the Russian Empire between 1904 and 1905. The Japanese won the war in 1905, and the Russians lost. The war happened because the Russian Empire and the Empire of Japan disagreed over who should get parts of Manchuria and Korea. The war was fought mostly on the Liaodong Peninsula and Mukden, the seas around Korea, Japan, and the Yellow Sea. The politics of both countries in the war were very complicated. Both wanted to gain land and economic benefits. The Chinese Empire of the Qing Dynasty was large but weak. As a result, Japan and Russia saw an opportunity. Both countries wanted and fought over Qing land and possessions. Russia wanted a warm-water port on the Pacific Ocean for its navy and trade. The harbor at Vladivostok freezes over in the winter, but Port Arthur could be used all year round. Russia had already rented the port from the Qing and had permission to build a Trans-Siberian railway from St Petersburg to Port Arthur. Japan wanted to expand its empire into Korea and China. Japan thought that when Russia completed its railway in 1906, it would be able to beat Japan in a war by being able to supply large numbers of troops there. That obviously made the Japanese nervous, as tensions had been high. Japan wanted to compromise with Russia to avoid war, even if Russia got the better deal. Japan wanted more of Korea and China than it thought Russia would offer. Japan decided to attack before the railway was complete so that it could do well in a war against Russia. The war started with a Japanese surprise attack on Port Arthur and continued with Japanese victories in Manchuria and elsewhere. The last major battle was at Tsushima Strait, which destroyed the Russian Navy.",
      GL: "8.7",
      FRE: "60.2",
      dict: {
        against:       ["contra"],
        already:       ["ya"],
        around:        ["alrededor de"],
        Arthur:        ["Arturo"],
        be:            ["ser", "estar"],
        beat:          ["vencer", "derrotar"],
        because:       ["porque"],
        being:         ["siendo", "estar"],
        benefits:      ["beneficios"],
        between:       ["entre"],
        both:          ["ambos"],
        build:         ["construir"],
        chinese:       ["chino"],
        complete:      ["completar", "completo"],
        completed:     ["completó", "completara"],
        complicated:   ["complicada"],
        compromise:    ["llegar a un acuerdo", "compromiso"],
        continued:     ["continuó"],
        could:         ["podría", "podía"],
        countries:     ["países"],
        decided:       ["decidió"],
        destroyed:     ["destruyó"],
        disagreed:     ["discreparon", "no estuvieron de acuerdo"],
        dynasty:       ["dinastía"],
        economic:      ["económicos"],
        elsewhere:     ["en otros lugares"],
        freezes:       ["se congela"],
        fought:        ["luchó", "se libró"],
        gain:          ["ganar", "obtener"],
        happened:      ["ocurrió", "sucedió"],
        high:          ["altas", "alto"],
        japanese:      ["japonés", "japoneses"],
        Korea:         ["Corea"],
        liaodong:      ["Liaodong"],
        Manchuria:     ["Manchuria"],
        Mukden:        ["Mukden"],
        nervous:       ["nerviosos"],
        numbers:       ["números", "cantidades"],
        obviously:     ["obviamente"],
        ocean:         ["océano"],
        opportunity:   ["oportunidad"],
        pacific:       ["Pacífico"],
        peninsula:     ["península"],
        permission:    ["permiso"],
        petersburg:    ["Petersburgo"],
        politics:      ["política"],
        possessions:   ["posesiones"],
        railway:       ["ferrocarril"],
        round:         ["todo el año", "redondo"],
        russian:       ["ruso"],
        russians:      ["rusos"],
        sea:           ["mar"],
        seas:          ["mares"],
        should:        ["debería"],
        siberian:      ["siberiano"],
        started:       ["comenzó", "empezó"],
        strait:        ["estrecho"],
        surprise:      ["sorpresa"],
        tensions:      ["tensiones"],
        thought:       ["pensó", "creía"],
        took:          ["tuvo lugar", "tomó"],
        troops:        ["tropas"],
        Tsushima:      ["Tsushima"],
        victories:     ["victorias"],
        vladivostok:   ["Vladivostok"],
        weak:          ["débil"],
        which:         ["cual", "que"],
        would:         ["podría", "sería"],
        year:          ["año"]
      },
      questions: [
        { q: "What was the cause of the Russo-Japanese War?", options: ["The war happened because of a sovereignty disagreement over Manchuria and Korea.", "China gave the port to Korea, but Russia had already built the Trans-Siberian railway there from Moscow.", "Russia rented the port from the Qing, but Japan destroyed the Russian Navy in a surprise attack.", "The port in Vladivostok was widely regarded as one of the most strongly fortified positions in the world, and both countries wanted it for security purposes."], answer: "A" },
        { q: "Why did Russia want the port?", options: ["The Qing gave the port to Russia who connected it to the rest of Russia by a railway. ", "The port linked the Black Sea with the Mediterranean Sea for trade.", "Russia wanted the strategically located port for security purposes.", "Russia wanted a warm-water port on the Pacific Ocean for its navy and trade."], answer: "D" },
        { q: "Where was the Japanese surprise attack?", options: ["Port Mukden", "Pacific Ocean Port", "Liaodong Peninsula", "Port Arthur"], answer: "D" }
      ]
    }, 

    { 
    id: "p4",
    text: "In 1984, British scientists cloned the first mammals by splitting a sheep embryo. At the time, no one thought it possible to clone an adult animal, but scientists at the Roslin Institute in Scotland persisted and succeeded. They used an adult sheep’s stem cell, found in bone marrow or mammary glands, and transferred the nucleus to another cell to create the embryo. On July 5, 1996, Dolly was born to a surrogate mother. The news of her birth thrilled the public and the scientific world. Although many people believe Dolly was the first clone, her birth was exciting because she was cloned from an adult sheep. This opened up the field of stem cell research. Stem cells are our most basic cells that can develop into any other kind of cell—from muscle to brain cells. Scientists are studying how they can heal damaged tissue or organs, perhaps even helping paralyzed people walk again someday. Dolly’s birth, life, and death also brought ethical issues to the forefront. While stem cell research and cloning technology can and are certainly helping people, some debate whether it's a slippery slope toward radical human genetic engineering. The risks of designer babies or potentially deformed human clones are often mentioned, but the reality is that science is far from able to clone or even elect specific genetic traits. There is still much more to study before humanity is close to that possibility. Dolly’s life was short; she died at six years old though sheep usually live for twice as long. What scientists realized is that specific proteins in her DNA called telomeres were much shorter than other sheep her age. Telomeres get shorter as we age, and Dolly’s were as short as her clone. This begged the question: when Dolly was born, was her DNA already the “same age” as her clone? Furthermore, what implications did that have for the future study of cloning?",
    GL:"8.8",
    FRE:"64.4",
    dict: {
      again:         ["de nuevo", "otra vez"],
      already:       ["ya"],
      although:      ["aunque"],
      another:       ["otro", "otra"],
      babies:        ["bebés"],
      because:       ["porque"],
      believe:       ["creen"],
      birth:         ["nacimiento"],
      brain:         ["cerebro"],
      british:       ["británicos"],
      brought:       ["trajo"],
      
      certainly:     ["ciertamente", "sin duda"],
      cloning:       ["clonación"],
      create:        ["crear"],
      damaged:       ["dañado"],
      death:         ["muerte"],
      deformed:      ["deformes"],
      designer:      ["de diseño"],
      develop:       ["convertirse en", "desarrollarse"],
      died:          ["murió"],
      engineering:   ["ingeniería"],
      ethical:       ["éticas"],
      exciting:      ["emocionante"],
      field:         ["campo"],
      forefront:     ["primer plano", "vanguardia"],
      found:         ["encontrado", "que se encuentra"],
      furthermore:   ["además"],
      genetic:       ["genética"],
      heal:          ["sanar", "curar"],
      helping:       ["ayudando"],
      humanity:      ["humanidad"],
      implications:  ["implicaciones"],
      institute:     ["instituto"],
      mammals:       ["mamíferos"],
      mammary:       ["mamarias"],
      mentioned:     ["mencionados"],
      mother:        ["madre"],
      nucleus:       ["núcleo"],
      other:         ["otro", "otras"],
      paralyzed:     ["paralizadas"],
      perhaps:       ["quizás", "tal vez"],
      persisted:     ["persistieron", "insistieron"],
      possibility:   ["posibilidad"],
      possible:      ["posible"],
      potentially:   ["potencialmente"],
      proteins:      ["proteínas"],
      question:      ["pregunta"],
      radical:       ["radical"],
      reality:       ["realidad"],
      realized:      ["se dieron cuenta"],
      research:      ["investigación"],
      roslin:        ["roslin"],
      science:       ["ciencia"],
      scientific:    ["científico"],
      scientists:    ["científicos"],
      scotland:      ["Escocia"],
      sheep:         ["oveja"],
      short:         ["corta", "corto"],
      shorter:       ["más cortos", "más corta"],
      slippery:      ["resbaladiza"],
      someday:       ["algún día"],
      specific:      ["específicos"],
      splitting:     ["dividir", "separar"],
      studying:      ["estudiando"],
      succeeded:     ["lo lograron", "tuvieron éxito"],
      technology:    ["tecnología"],
      telomeres:     ["telómeros"],

      though:        ["aunque"],
      thought:       ["pensó", "creía"],
      thrilled:      ["emocionó", "entusiasmó"],
      traits:        ["rasgos"],
      transferred:   ["transfirieron"],
      whether:       ["si"],
      while:         ["mientras", "aunque"],
      years:         ["años"]
    },
    questions: [
        { q: "In which country was the first sheep cloned?", options: ["England", "Scotland", "China", "The United States"], answer: "B" },
        { q: "What was different about Dolly the sheep? ", options: ["She was cloned from an adult sheep.", "She lived longer than other sheep.", "She was the first cloned mammal. ", "She was cloned from another sheep embryo."], answer: "A" },
        { q: "Which was NOT an ethical concern mentioned in the text? ", options: ["Radical human genetic engineering", "Designer babies", "Helping paralyzed people walk someday", "Deformed human clones"], answer: "C" } 
    ]
}];
   
